services:
  backend:
    image: dukeyico/java-backend:latest
    volumes:
      - ./backend/src:/app/src
    build: ./backend
    container_name: java-backend
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/pom.xml
  

    ports:
      - "8080:8080"
  frontend:
    image: dukeyico/web-frontend:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    build: ./frontend
    container_name: web-frontend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/share/nginx/html
    environment:
      - VITE_API_URL=http://20.0.250.3:8080/api/students
    ports:
      - "5173:80"
    depends_on:
      - backend